from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from types import MappingProxyType
from typing import Protocol

from .contexts import InvocationView
from .display import DisplayDocument
from .storage import GrantReference, JsonObject, JsonValue, OwnerScope, OwnershipKind


@dataclass(frozen=True, slots=True)
class DigestScheduleProfile:
    """User-selected daily digest window policy persisted with a subscription.

    local_time is the daily local due boundary. The boundary is resolved with
    the stored fold/gap policy; duration is elapsed UTC time preceding that
    boundary, and due time is exactly the resulting end.
    """

    timezone_name: str
    local_time: str
    window_duration_seconds: int
    fold_policy: "DstFoldPolicy"
    gap_policy: "DstGapPolicy"
    policy_revision: int = 1


@dataclass(frozen=True, slots=True)
class SubscriptionRequest:
    """Command data; account, module and route authority is resolved by core.

    An omitted ID/revision denotes CREATE. Both are required for REVISE.
    Creation IDs are generated by the core and cannot be supplied here.
    """

    type_id: str
    collector_parameters: JsonObject
    filters: JsonObject
    notification_mode: str
    digest_schedule: DigestScheduleProfile | None = None
    subscription_id: str | None = None
    expected_revision: int | None = None

    def __post_init__(self) -> None:
        if isinstance(self.collector_parameters, Mapping):
            object.__setattr__(
                self,
                "collector_parameters",
                MappingProxyType(dict(self.collector_parameters)),
            )
        if isinstance(self.filters, Mapping):
            object.__setattr__(self, "filters", MappingProxyType(dict(self.filters)))


@dataclass(frozen=True, slots=True)
class NormalizedInput:
    """Canonical, schema-validated collector parameters supplied by a module."""

    values: JsonObject

    def __post_init__(self) -> None:
        if isinstance(self.values, Mapping):
            object.__setattr__(self, "values", MappingProxyType(dict(self.values)))


@dataclass(frozen=True, slots=True)
class CollectionKey:
    module_id: str
    collector_id: str
    key_version: int
    source_id: str
    parameters: NormalizedInput
    scope: OwnerScope


class ObservationCompleteness(str, Enum):
    COMPLETE = "complete"
    PARTIAL = "partial"
    FAILED = "failed"


class ConversationKind(str, Enum):
    DIRECT = "direct"
    GROUP = "group"


@dataclass(frozen=True, slots=True)
class ConversationRef:
    adapter_id: str
    kind: ConversationKind
    conversation_id: str
    delivery_route: str


class DstFoldPolicy(str, Enum):
    FIRST_OCCURRENCE = "first_occurrence"
    SECOND_OCCURRENCE = "second_occurrence"


class DstGapPolicy(str, Enum):
    SKIP = "skip"
    NEXT_VALID_INSTANT = "next_valid_instant"


@dataclass(frozen=True, slots=True)
class Observation:
    """An immutable collector snapshot; its payload is opaque to the runtime."""

    observation_id: str
    key: CollectionKey
    data_version: int
    source_observed_at: datetime | None
    collected_at: datetime
    completeness: ObservationCompleteness
    covered_ids: tuple[str, ...]
    payload: JsonObject

    def __post_init__(self) -> None:
        if self.covered_ids is not None:
            object.__setattr__(self, "covered_ids", tuple(self.covered_ids))
        if isinstance(self.payload, Mapping):
            object.__setattr__(self, "payload", MappingProxyType(dict(self.payload)))


@dataclass(frozen=True, slots=True)
class SubscriptionView:
    """Read-only revision of one subscription visible to its matcher."""

    subscription_id: str
    revision: int
    owner_id: str
    grant: GrantReference | None
    notification_conversation_id: str
    filters: JsonObject

    def __post_init__(self) -> None:
        if isinstance(self.filters, Mapping):
            object.__setattr__(self, "filters", MappingProxyType(dict(self.filters)))


@dataclass(frozen=True, slots=True)
class EvaluationState:
    revision: int
    value: JsonValue


@dataclass(frozen=True, slots=True)
class EvaluationDecision:
    """Pure matcher output, committed atomically by the owning service."""

    state: JsonValue
    triggered: bool
    event_key: str | None = None
    event_version: int | None = None
    display_data: DisplayDocument | None = None


@dataclass(frozen=True, slots=True)
class CollectionView:
    key: CollectionKey
    deadline_monotonic: float | None = None
    invocation: InvocationView | None = None


class Collector(Protocol):
    def normalize(self, parameters: JsonObject) -> NormalizedInput: ...

    async def collect(
        self,
        context: CollectionView,
        parameters: NormalizedInput,
        previous: Observation | None,
    ) -> Observation: ...


class SubscriptionEvaluator(Protocol):
    """A synchronous pure matcher: it must not issue network or storage IO."""

    def evaluate(
        self,
        subscription: SubscriptionView,
        observation: Observation,
        previous_state: EvaluationState | None,
    ) -> EvaluationDecision: ...


@dataclass(frozen=True, slots=True)
class IntervalLimits:
    requested_seconds: float
    module_minimum_seconds: float
    runtime_minimum_seconds: float

    @property
    def target_seconds(self) -> float:
        return max(
            self.requested_seconds,
            self.module_minimum_seconds,
            self.runtime_minimum_seconds,
        )


@dataclass(frozen=True, slots=True)
class ScheduleDescriptor:
    collector_id: str
    key_version: int
    source_id: str
    data_version: int
    input_schema: JsonObject
    shared_scope: OwnershipKind
    trigger: "ScheduleTrigger"
    minimum_interval_seconds: float
    default_interval_seconds: float | None = None
    interval_config_key: str | None = None

    def __post_init__(self) -> None:
        if isinstance(self.input_schema, Mapping):
            object.__setattr__(
                self, "input_schema", MappingProxyType(dict(self.input_schema))
            )


class ScheduleTrigger(str, Enum):
    PERIODIC = "periodic"
    ON_DEMAND = "on_demand"


@dataclass(frozen=True, slots=True)
class SubscriptionDescriptor:
    type_id: str
    collector_id: str
    matcher_id: str
    filter_schema: JsonObject
    notification_modes: tuple[str, ...]

    def __post_init__(self) -> None:
        if isinstance(self.filter_schema, Mapping):
            object.__setattr__(
                self, "filter_schema", MappingProxyType(dict(self.filter_schema))
            )
        if self.notification_modes is not None:
            object.__setattr__(
                self, "notification_modes", tuple(self.notification_modes)
            )
